### ISSUE TITLE
Release Checklist 

### ISSUE THREAD

**Issue by aurielfournier** [datacarpentry/R-ecology-lesson#208]
## Lesson Release checklist

Scheduled Freeze Date:   2017-03-15  
Scheduled Release Date:  2017-04-21  

Checklist of tasks to complete before release:

- [x] check that the learning objectives reflect the content of the lessons
- [x] check that learning objectives are phrased as statements using action words
- [x] check for typos
- [x] check that the live coding examples work as expected
- [x] if example code generates warnings, explain in narrative and instructor notes
- [x] check that challenges and their solutions work as expected
- [x] check that the challenges test skills that have been seen
- [x] check that the setup instructions are up to date (e.g., update version numbers)
- [x] check that data is available and mentions of the data in the lessons are accurate
- [x] check that the instructor guide is up to date with the content of the lessons
- [x] check that all the links within the lessons work (this should be automated)
- [x] make sure formatting of the code in the lesson looks good (e.g. line breaks)
- [x] check for clarity and flow of narrative
- [x] update README as needed
- [ ] fill out “overview” for each module - minutes needed for teaching and exercises, questions and learning objectives
- [x] check that contributor guidelines are clear and consistent
- [x] clean up files (e.g. delete deprecated files, insure filenames are consistent)
- [ ] update the release notes (NEWS)
- [ ] tag release on GitHub

**Comment by aurielfournier** [comment]
Checked all links. Submitted Issue for the broken 1 that I found.
