### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/R-ecology-lesson#535]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [ ] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [ ] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [ ] Each episode includes learning objectives
- [ ] Each episode includes questions
- [ ] Each episode includes key points
- [ ] Setup instructions are up-to-date, correct, clear, and complete
- [ ] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [ ] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Hi @fmichonneau, @aurielfournier, @anacost and @mondorescue - Just confirming that you're still planning on including your lesson in the June 2019 release. We'll be putting out a blog post tomorrow inviting contributors to work on issues that have been tagged as part of the release milestone, so if there are specific issues you're looking for community help with, please add them to that milestone. I'll go ahead and do that too for the "help-wanted" issues. Please let me know if you have any questions!

**Comment by ErinBecker** [comment]
Hey Maintainers - just checking in to see if you're still planning on joining the release this month. We're asking that all lessons have completed the checklist by [Tuesday, 4 June, Anywhere on Earth time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20190604T235959&p1=3399) in order to be included in the release. Please let me and @fmichonneau know if you have any questions or are running into any technical issues with preparing your lesson.

**Comment by ErinBecker** [comment]
Hey @fmichonneau - Looks like the checklist for this lesson didn't get ticked off. I'm working on the blog post announcing the release for next week and wondering whether this lesson should be included. Please let me know (or close the issue). Thanks!

**Comment by fmichonneau** [comment]
Most of the boxes that didn't get ticked is because the template used by this lesson is a little different and doesn't apply here. The lesson is otherwise in good shape.

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3264888
